2025-05-14 09:24:47 [ERROR] Failed to upload file to HDFS: 
2025-05-14 09:22:09,193 WARN hdfs.DFSUtilClient: Namenode for hadoop-cluster remains unresolved for ID nn1. Check your hdfs-site.xml file to ensure namenodes are configured properly.
2025-05-14 09:22:09,802 WARN hdfs.DFSUtilClient: Namenode for hadoop-cluster remains unresolved for ID nn2. Check your hdfs-site.xml file to ensure namenodes are configured properly.
2025-05-14 09:22:10,030 WARN hdfs.DFSUtilClient: Namenode for hadoop-cluster remains unresolved for ID nn3. Check your hdfs-site.xml file to ensure namenodes are configured properly.
2025-05-14 09:22:13,444 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m1:8020 after 3 failover attempts. Trying to failover after sleeping for 2033ms. Current retry count: 3.
2025-05-14 09:22:15,481 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m2:8020 after 4 failover attempts. Trying to failover after sleeping for 8311ms. Current retry count: 4.
2025-05-14 09:22:24,027 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m3:8020 after 5 failover attempts. Trying to failover after sleeping for 14631ms. Current retry count: 5.
2025-05-14 09:22:38,858 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m1:8020 after 6 failover attempts. Trying to failover after sleeping for 14650ms. Current retry count: 6.
2025-05-14 09:22:53,695 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m2:8020 after 7 failover attempts. Trying to failover after sleeping for 13484ms. Current retry count: 7.
2025-05-14 09:23:07,580 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m3:8020 after 8 failover attempts. Trying to failover after sleeping for 13105ms. Current retry count: 8.
2025-05-14 09:23:20,784 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m1:8020 after 9 failover attempts. Trying to failover after sleeping for 17307ms. Current retry count: 9.
2025-05-14 09:23:38,192 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m2:8020 after 10 failover attempts. Trying to failover after sleeping for 13461ms. Current retry count: 10.
2025-05-14 09:23:51,756 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m3:8020 after 11 failover attempts. Trying to failover after sleeping for 14570ms. Current retry count: 11.
2025-05-14 09:24:06,538 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m1:8020 after 12 failover attempts. Trying to failover after sleeping for 21232ms. Current retry count: 12.
2025-05-14 09:24:27,876 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m2":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m2:8020 after 13 failover attempts. Trying to failover after sleeping for 9791ms. Current retry count: 13.
2025-05-14 09:24:37,821 INFO retry.RetryInvocationHandler: java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m3":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost, while invoking ClientNamenodeProtocolTranslatorPB.getFileInfo over m3:8020 after 14 failover attempts. Trying to failover after sleeping for 8713ms. Current retry count: 14.
put: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException: Invalid host name: local host is: "438ef43eee61/172.24.0.2"; destination host is: "m1":8020; java.net.UnknownHostException; For more details see:  http://wiki.apache.org/hadoop/UnknownHost; For more details see:  http://wiki.apache.org/hadoop/UnknownHost

2025-05-14 09:24:47 [INFO] Local file /home/hadoop/tmp/loans_time.parquet removed after upload.
2025-05-14 09:24:47 [ERROR] Pipeline failed for file: loans, HDFS upload failed.
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:24:50 [INFO] Processing file: support_tickets
2025-05-14 09:24:50 [INFO] Extracted support_tickets: 
columns => ['ticket_id', 'customer_id', 'complaint_category', 'complaint_date', 'severity'] 
rows => 15000
2025-05-14 09:24:50 [INFO] support_tickets schema validation passed.
2025-05-14 09:24:50 [INFO] Transformed support_tickets: 
columns => ['ticket_id', 'customer_id', 'complaint_category', 'complaint_date', 'severity', 'age', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 15000
2025-05-14 09:24:50 [INFO] Data successfully written to ./tmp/support_tickets_time.parquet
2025-05-14 09:34:51 [INFO] Processing file: support_tickets
2025-05-14 09:34:51 [INFO] Extracted support_tickets: 
columns => ['ticket_id', 'customer_id', 'complaint_category', 'complaint_date', 'severity'] 
rows => 15000
2025-05-14 09:34:51 [INFO] support_tickets schema validation passed.
2025-05-14 09:34:51 [INFO] Transformed support_tickets: 
columns => ['ticket_id', 'customer_id', 'complaint_category', 'complaint_date', 'severity', 'age', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 15000
2025-05-14 09:34:51 [INFO] Data successfully written to ./tmp/support_tickets_time.parquet
2025-05-14 09:34:56 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/support_tickets_time.parquet', '/stage/support_tickets']' timed out after 5 seconds
2025-05-14 09:34:56 [INFO] Local file /home/hadoop/tmp/support_tickets_time.parquet removed after upload.
2025-05-14 09:34:56 [ERROR] Pipeline failed for file: support_tickets with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/support_tickets_time.parquet', '/stage/support_tickets']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:34:59 [INFO] Processing file: credit_cards_billing
2025-05-14 09:35:00 [INFO] Extracted credit_cards_billing: 
columns => ['bill_id', 'customer_id', 'month', 'amount_due', 'amount_paid', 'payment_date'] 
rows => 200000
2025-05-14 09:35:00 [INFO] credit_cards_billing schema validation passed.
2025-05-14 09:35:00 [INFO] Transformed credit_cards_billing: 
columns => ['bill_id', 'customer_id', 'month', 'amount_due', 'amount_paid', 'payment_date', 'fully_paid', 'debt', 'due_date', 'late_days', 'fine', 'total_amount', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 200000
2025-05-14 09:35:00 [INFO] Data successfully written to ./tmp/credit_cards_billing_time.parquet
2025-05-14 09:35:05 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/credit_cards_billing_time.parquet', '/stage/credit_cards_billing']' timed out after 5 seconds
2025-05-14 09:35:05 [INFO] Local file /home/hadoop/tmp/credit_cards_billing_time.parquet removed after upload.
2025-05-14 09:35:05 [ERROR] Pipeline failed for file: credit_cards_billing with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/credit_cards_billing_time.parquet', '/stage/credit_cards_billing']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:35:07 [INFO] Processing file: transactions
2025-05-14 09:35:08 [INFO] Extracted transactions: 
columns => ['sender', 'receiver', 'transaction_amount', 'transaction_date'] 
rows => 100000
2025-05-14 09:35:08 [INFO] transactions schema validation passed.
2025-05-14 09:35:08 [INFO] Transformed transactions: 
columns => ['sender', 'receiver', 'transaction_amount', 'transaction_date', 'cost', 'total_amount', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 100000
2025-05-14 09:35:08 [INFO] Data successfully written to ./tmp/transactions_time.parquet
2025-05-14 09:35:13 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/transactions_time.parquet', '/stage/transactions']' timed out after 5 seconds
2025-05-14 09:35:13 [INFO] Local file /home/hadoop/tmp/transactions_time.parquet removed after upload.
2025-05-14 09:35:13 [ERROR] Pipeline failed for file: transactions with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/transactions_time.parquet', '/stage/transactions']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:35:16 [INFO] Processing file: customer_profiles
2025-05-14 09:35:17 [INFO] Extracted customer_profiles: 
columns => ['customer_id', 'name', 'gender', 'age', 'city', 'account_open_date', 'product_type', 'customer_tier'] 
rows => 100000
2025-05-14 09:35:17 [INFO] customer_profiles schema validation passed.
2025-05-14 09:35:17 [INFO] Transformed customer_profiles: 
columns => ['customer_id', 'name', 'gender', 'age', 'city', 'account_open_date', 'product_type', 'customer_tier', 'tenure', 'customer_segment', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 100000
2025-05-14 09:35:17 [INFO] Data successfully written to ./tmp/customer_profiles_time.parquet
2025-05-14 09:35:22 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/customer_profiles_time.parquet', '/stage/customer_profiles']' timed out after 5 seconds
2025-05-14 09:35:22 [INFO] Local file /home/hadoop/tmp/customer_profiles_time.parquet removed after upload.
2025-05-14 09:35:22 [ERROR] Pipeline failed for file: customer_profiles with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/customer_profiles_time.parquet', '/stage/customer_profiles']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:37:54 [INFO] Processing file: loans
2025-05-14 09:37:54 [INFO] Extracted loans: 
columns => ['customer_id', 'loan_type', 'amount_utilized', 'utilization_date', 'loan_reason'] 
rows => 1000
2025-05-14 09:37:54 [INFO] loans schema validation passed.
2025-05-14 09:37:54 [INFO] Transformed loans: 
columns => ['customer_id', 'loan_type', 'amount_utilized', 'utilization_date', 'loan_reason', 'age', 'total_cost', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 1000
2025-05-14 09:37:54 [INFO] Data successfully written to ./tmp/loans_time.parquet
2025-05-14 09:37:59 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/loans_time.parquet', '/stage/loans']' timed out after 5 seconds
2025-05-14 09:37:59 [ERROR] Local file /home/hadoop/tmp/loans_time.parquet removed after failed upload.
2025-05-14 09:37:59 [ERROR] Pipeline failed for file: loans with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/loans_time.parquet', '/stage/loans']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:38:03 [INFO] Processing file: support_tickets
2025-05-14 09:38:03 [INFO] Extracted support_tickets: 
columns => ['ticket_id', 'customer_id', 'complaint_category', 'complaint_date', 'severity'] 
rows => 15000
2025-05-14 09:38:03 [INFO] support_tickets schema validation passed.
2025-05-14 09:38:03 [INFO] Transformed support_tickets: 
columns => ['ticket_id', 'customer_id', 'complaint_category', 'complaint_date', 'severity', 'age', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 15000
2025-05-14 09:38:03 [INFO] Data successfully written to ./tmp/support_tickets_time.parquet
2025-05-14 09:38:08 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/support_tickets_time.parquet', '/stage/support_tickets']' timed out after 5 seconds
2025-05-14 09:38:08 [ERROR] Local file /home/hadoop/tmp/support_tickets_time.parquet removed after failed upload.
2025-05-14 09:38:08 [ERROR] Pipeline failed for file: support_tickets with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/support_tickets_time.parquet', '/stage/support_tickets']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:38:11 [INFO] Processing file: transactions
2025-05-14 09:38:11 [INFO] Extracted transactions: 
columns => ['sender', 'receiver', 'transaction_amount', 'transaction_date'] 
rows => 100000
2025-05-14 09:38:11 [INFO] transactions schema validation passed.
2025-05-14 09:38:11 [INFO] Transformed transactions: 
columns => ['sender', 'receiver', 'transaction_amount', 'transaction_date', 'cost', 'total_amount', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 100000
2025-05-14 09:38:11 [INFO] Data successfully written to ./tmp/transactions_time.parquet
2025-05-14 09:38:16 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/transactions_time.parquet', '/stage/transactions']' timed out after 5 seconds
2025-05-14 09:38:16 [ERROR] Local file /home/hadoop/tmp/transactions_time.parquet removed after failed upload.
2025-05-14 09:38:16 [ERROR] Pipeline failed for file: transactions with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/transactions_time.parquet', '/stage/transactions']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
2025-05-14 09:38:20 [INFO] Processing file: customer_profiles
2025-05-14 09:38:20 [INFO] Extracted customer_profiles: 
columns => ['customer_id', 'name', 'gender', 'age', 'city', 'account_open_date', 'product_type', 'customer_tier'] 
rows => 100000
2025-05-14 09:38:20 [INFO] customer_profiles schema validation passed.
2025-05-14 09:38:20 [INFO] Transformed customer_profiles: 
columns => ['customer_id', 'name', 'gender', 'age', 'city', 'account_open_date', 'product_type', 'customer_tier', 'tenure', 'customer_segment', 'processing_time', 'partition_date', 'partition_hour'] 
rows => 100000
2025-05-14 09:38:20 [INFO] Data successfully written to ./tmp/customer_profiles_time.parquet
2025-05-14 09:38:25 [ERROR] Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/customer_profiles_time.parquet', '/stage/customer_profiles']' timed out after 5 seconds
2025-05-14 09:38:25 [ERROR] Local file /home/hadoop/tmp/customer_profiles_time.parquet removed after failed upload.
2025-05-14 09:38:25 [ERROR] Pipeline failed for file: customer_profiles with error: 
Failed to upload file to HDFS: Command '['hdfs', 'dfs', '-put', '/home/hadoop/tmp/customer_profiles_time.parquet', '/stage/customer_profiles']' timed out after 5 seconds 
 ==========================================================================================================================================================================================================================================================
